# Generated by Django 3.0.2 on 2020-02-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='websites'),
        ),
    ]
