# Generated by Django 3.0.2 on 2020-02-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_website_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='websites'),
        ),
    ]
