# Generated by Django 3.0.2 on 2020-03-13 01:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20200227_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
